### PR TITLE
Replace the jump [src] text with an icon

### PR DESCRIPTION
**Pull request by hashrock**
before: 
image

after:

image

### CODE REVIEW

**Review by crowlKats — CHANGES_REQUESTED** [review]
A hover state should be added

**Comment by hashrock** [comment]
@crowlKats 

I changed to use the default text hover style. It looks subtle but okay? (or do we need add background color?)

20221017-hover-doc

**Comment by crowlKats** [comment]
hm seems a bit too subtle, so maybe yea, a background color would be nice

**Comment by hashrock** [comment]
@crowlKats done! PTAL:

20221018-hover-doc

**Review by crowlKats — APPROVED** [review]
LGTM!

**Pull request merged**
