### PR TITLE
refactor: switch comrak to gfm

### PR DESCRIPTION
**Pull request by crowlKats**

### CODE REVIEW

**Comment by crowlKats** [comment]
maybe we should re-export gfm due to having to manually serve the CSS

**Comment by kitsonk** [comment]
I am not totally happy with this for a couple of things:

- The solution provides syntax highlighting, which is 15k of CSS that you have to deliver on each page, wether it is used or not.
- The existing solution also provides syntax highlighting which wasn't refactored out.
- The existing solution also uses twind for all the CSS, meaning it is optimised on every render, with only the styles actually used being sent in the payload.
- The existing solution provides easy ways to [adjust the styling](https://github.com/denoland/doc_components/blob/main/styles.ts#L20-L49) which is in line with everything else about doc_components.

If it didn't provide "static" CSS and instead used twind, I would be supportive.  The [showcase page](https://deno-doc-components.deno.dev/), which includes pretty much every style, is 21k of CSS, adding another 15k of CSS wether you need all/some/none and not being easily adjustable from a styling/theming perspective makes it a concern for me.

**Comment by kitsonk** [comment]
I am not totally happy with this for a couple of things:

- The solution provides syntax highlighting, which is 15k of CSS that you have to deliver on each page, wether it is used or not.
- The existing solution also provides syntax highlighting which wasn't refactored out.
- The existing solution also uses twind for all the CSS, meaning it is optimised on every render, with only the styles actually used being sent in the payload.
- The existing solution provides easy ways to [adjust the styling](https://github.com/denoland/doc_components/blob/main/styles.ts#L20-L49) which is in line with everything else about doc_components.

If it didn't provide "static" CSS and instead used twind, I would be supportive.  The [showcase page](https://deno-doc-components.deno.dev/), which includes pretty much every style, is 21k of CSS, adding another 15k of CSS wether you need all/some/none and not being easily adjustable from a styling/theming perspective makes it a concern for me.

**Comment by crowlKats** [comment]
Closing in favour of #14

**Pull request closed without merging**
